apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-registry
  labels:
    app: registry
    distribution-release: {{ .Release.Name}}
spec:
  ports:
    - port: 5000
      name: registry
      nodePort: {{ .Values.distribution.nodePort }}
      targetPort: 5000
  type: NodePort
  selector:
    app: registry
    distribution-release: {{ .Release.Name}}
