apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-registry-configmap
data:
  config.yml: |
    version: 0.1
    log:
      fields:
        service: {{ .Release.Name}}-registry
    storage:
{{ if .Values.redis.enabled }}
      cache:
        blobdescriptor: redis
{{ end }}
      filesystem:
        rootdirectory: /var/lib/registry-cache
      maintenance:
        uploadpurging:
          enabled: false
{{ if .Values.redis.enabled }}
    redis:
      addr: {{ .Release.Name}}-redis:6379
      pool:
        maxidle: 16
        maxactive: 64
        idletimeout: 300s
      dialtimeout: 10ms
      readtimeout: 10ms
      writetimeout: 10ms
{{ end }}
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    {{ if .Values.distribution.proxy }}
    proxy:
      remoteurl: {{ .Values.distribution.proxy }}
    {{ end }}

    
