{{if  .Values.gatewaybridge.service.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-gb-configmap
  namespace: {{ .Release.Namespace }}
data:
  chirpstack-gateway-bridge.toml: |
    # See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
    # configuration example and documentation.

    [integration.mqtt.auth.generic]
    servers=["tcp://{{ .Release.Name }}-{{ .Values.mosquitto.service.name | default "mosquitto"  }}.{{ .Release.Namespace }}:1883"]
    username=""
    password=""
    
{{end}}