{{if  .Values.gatewaybridge.service.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gatewaybridge.service.name | default "gateway-bridge"  }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: gateway-bridge
spec:
  ports:
    - port: 1700
      name: gateway-bridge
      protocol: UDP
  type: ClusterIP
  selector:
    app: gateway-bridge
    
{{end}}
