apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ns
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "chirpstack.matchLabels" . | nindent 6 }}
      app: chirpstack-ns
  replicas: 1
  template:
    metadata:
      labels:
        app: chirpstack-ns
        {{- include "chirpstack.template.labels" . | nindent 8 }}
    spec:
{{- if .Values.chirpstack.common.nodeSelector.enabled }}
      nodeSelector:
        {{- include "chirpstack.nodeSelector" . | nindent 8 }}
{{- end }}
      terminationGracePeriodSeconds: 30
      initContainers:
      - name: wait-redis
        image: busybox:1.31
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nslookup {{ .Release.Name }}-{{ .Values.redis.service.name | default "redis"  }}; do echo waiting for redis; sleep 2; done;']
      - name: wait-mqtt
        image: busybox:1.31
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nslookup {{ .Release.Name }}-{{ .Values.mosquitto.service.name | default "mosquitto"  }}; do echo waiting for mqtt; sleep 2; done;']
      - name: wait-postgresql
        image: busybox:1.31
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nslookup {{ .Release.Name }}-{{ .Values.postgresql.service.name | default "pgsql"  }}; do echo waiting for postgresql; sleep 2; done;']
      containers:
      - name: chirpstack-ns
        image: {{ .Values.networkserver.image }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: configfile
          mountPath: /etc/chirpstack-network-server
      volumes:
      - name: configfile
        configMap:
          name:  {{ .Release.Name}}-ns-configmap