# Default values for distribution.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

distribution:
  proxy: "https://gcr.io"
  image:
    repository: distribution/distribution
    pullPolicy: IfNotPresent
    tag: "2.8.1"
  nodePort: 30001

redis:
  enabled: false
  storageClassName: standard
  image:
    repository: redis
    pullPolicy: IfNotPresent
    tag: "6.2.4"

minio:
  enabled: false
  storageClassName: standard
  image:
    repository: quay.io/minio/minio
    pullPolicy: IfNotPresent
    tag: "RELEASE.2021-09-24T00-24-24Z"

