apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: cef
      port: 8080
  type: ClusterIP
  selector:
    app: chirpstack-event-forward
