apiVersion: v1
kind: Service
metadata:
  name: {{ include "xline.fullname" . }}
  labels:
    {{- include "xline.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "xline.selectorLabels" . | nindent 4 }}
