{{ if .Values.pulsar.tls.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-delete-ca
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 0
  template:
    metadata:
      name: {{ .Release.Name }}-delete-ca
      labels:
        app: {{ .Release.Name }}-delete-ca
    spec:
      serviceAccountName: {{ .Release.Name }}-pulsar
      containers:
      - name: kubectl
        image: bitnami/kubectl:1.21.5
        command: ["sh","-c","kubectl delete secret {{ .Release.Name }}-pulsar -n {{ .Release.Namespace }}"]
      restartPolicy: Never
{{ end }}