apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-pulsar
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-pulsar
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-pulsar
rules:
- apiGroups:
  - "*"
  resources:
  - jobs
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-pulsar
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-pulsar
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-pulsar
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-pulsar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-pulsar
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-pulsar
  namespace: {{ .Release.Namespace }}
---