apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.mosquitto.service.name | default "mosquitto"  }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: mosquitto
spec:
  ports:
    - port: 1883
      name: mosquitto
      {{- if .Values.mosquitto.service.stableNodePort }}
      nodePort: {{ .Values.mosquitto.service.nodePort }}
      {{- end }}
  type: {{ .Values.mosquitto.service.type }}
  selector:
    app: mosquitto
