gatewaybridge:
  service:
    name: gateway-bridge
    enable: false

mosquitto:
  image: eclipse-mosquitto:1.6.12
  service:
    name: mosquitto
    type: ClusterIP
    nodePort: 31883
    stableNodePort: false

appserver:
  replicas: 1
  image: chirpstack/chirpstack-application-server:3.17
  service:
    name: chirpstack-as
  ingress:
    enabled: false
    #className: "nginx"
    #annotations:
    host: chirpstack
    path: /
    pathType: ImplementationSpecific

networkserver:
  replicas: 1
  image: chirpstack/chirpstack-network-server:3.16
  service: 
    name: chirpstack-ns

postgresql:
  image: postgres:9.6-alpine
  service:
    name: pgsql
  spec:
    volumeClaimTemplates:
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 10Gi

redis:
  image: redis:6.0.9
  service:
    name: redis
  spec:
    volumeClaimTemplates:
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 1Gi


exporter:
  redis:
    image: oliver006/redis_exporter:v1.14.0
    service:
      name: redis-exporter

chirpstack:
  common:
    nodeSelector:
      enabled: false

pulsar:
  enabled: false