gatewaybridge:
  service:
    name: gateway-bridge
    enable: false

mosquitto:
  image: eclipse-mosquitto:1.6.12
  service:
    name: mosquitto
    type: ClusterIP
    nodePort: 31883
    stableNodePort: false

appserver:
  image: chirpstack/chirpstack-application-server:3
  service:
    name: chirpstack-as

networkserver:
  image: chirpstack/chirpstack-network-server:3
  service: 
    name: chirpstack-ns

postgresql:
  image: postgres:9.6-alpine
  service:
    name: pgsql
  spec:
    volumeClaimTemplates:
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 5G

redis:
  image: redis:6.0.9
  service:
    name: redis
  spec:
    volumeClaimTemplates:
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 500M


exporter:
  redis:
    image: oliver006/redis_exporter:v1.14.0
    service:
      name: redis-exporter

chirpstack:
  common:
    nodeSelector:
      enabled: false

pulsar:
  enabled: false