apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.redis.service.name | default "redis"  }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      name: redis
  type: ClusterIP
  selector:
    app: redis
