{{ if .Values.minio.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Release.Name}}-minio
  name: minio
spec:
  selector:
    matchLabels: 
      app: minio
  serviceName: {{ .Release.Name}}-minio
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag}}"
          name: minio
          env:
            - name: MINIO_ROOT_USER
              value: minioadmin
            - name: MINIO_ROOT_PASSWORD
              value: minioadmin
          ports:
          - name: minio
            containerPort: 9000
          - name: console
            containerPort: 9001
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: minio-vct
              mountPath: /data
          command: ['minio','server','/data','--console-address',':9001']
  volumeClaimTemplates:
    - metadata:
        name: minio-vct
      spec:
        storageClassName: {{ .Values.minio.storageClassName }}
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
{{ end }}