{{ if .Values.minio.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-minio
  labels:
    app: minio
spec:
  ports:
    - name: minio
      port: 9000
    - name: console
      port: 9001
  selector:
    app: minio
---
{{ end }}