apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-replacer
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-replacer
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingWebhookConfigurations
  verbs:
  - list
  - get
  - update
  - patch
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-replacer
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingWebhookConfiguration
  - mutatingwebhookconfigurations
  verbs:
  - "*"
- apiGroups:
  - "*"
  resources:
  - jobs
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - patch
  - get
---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: replacer
#   namespace: {{ .Release.Namespace }}
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: replacer
# subjects:
# - kind: ServiceAccount
#   name: replacer
#   namespace: {{ .Release.Namespace }}
# ---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-replacer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-replacer
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-replacer
  namespace: {{ .Release.Namespace }}
---