apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-replacer-create
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-replacer-create
    spec:
      containers:
      - args:
        - create
        - --host={{ .Release.Name }}-replacer,{{ .Release.Name }}-replacer.$(POD_NAMESPACE).svc
        - --namespace=$(POD_NAMESPACE)
        - --secret-name={{ .Release.Name }}-replacer
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: lank8s.cn/ingress-nginx/kube-webhook-certgen:v1.1.1
        imagePullPolicy: IfNotPresent
        name: create
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
      serviceAccountName: {{ .Release.Name }}-replacer
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-replacer-patch
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-replacer-patch
    spec:
      volumes:
      - secret:
          secretName: {{ .Release.Name }}-replacer
        name: tlsfile
      containers:
      - name: patch
        args:
        - patch
        - --webhook-name={{ .Release.Name }}-replacer
        - --namespace=$(POD_NAMESPACE)
        - --patch-mutating=true
        - --patch-validating=false
        - --secret-name={{ .Release.Name }}-replacer
        - --patch-failure-policy=Fail
        volumeMounts:
        - name: tlsfile
          mountPath: /tlsfile/
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: lank8s.cn/ingress-nginx/kube-webhook-certgen:v1.1.1
        imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
      serviceAccountName: {{ .Release.Name }}-replacer