apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-replacer
  labels:
    app: {{ .Release.Name }}-replacer
spec:
  ports:
    - port: 443
      targetPort: 8181
      name: replacer
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-replacer