apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Release.Name }}-replacer
  labels:
    app: {{ .Release.Name }}-replacer
webhooks:
  - name: {{ .Release.Name }}-replacer.{{ .Release.Namespace }}.svc
    admissionReviewVersions: ["v1beta1","v1"]
    sideEffects: None
    clientConfig:
      service:
        name: {{ .Release.Name }}-replacer
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
    rules:
      - operations: [ "CREATE","UPDATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments","daemonset","statefulset"]
      - operations: [ "CREATE","UPDATE" ]
        apiGroups: ["batch"]
        apiVersions: ["v1"]
        resources: ["jobs"]