apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-devpod
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-devpod
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-devpod
rules:
- apiGroups:
  - "*"
  resources:
  - jobs
  verbs:
  - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-devpod
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-devpod
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-devpod
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-devpod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-devpod
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-devpod
  namespace: {{ .Release.Namespace }}
---